import {KnowledgeGraph} from './knowledge-graph';

export type CurriculumProfile={
 subject:string;
 topic:string;
 concepts:string[];
 lesson:string;
 graph:KnowledgeGraph;
 questions:{type:'choice'|'concept';topic:string;prompt:string;options?:string[];answer:string;explanation:string}[];
};

const graph=(nodes:{id:string;name:string;description:string}[],edges:{from:string;to:string;reason:string}[]):KnowledgeGraph=>({nodes,edges});

const profiles:Record<string,Omit<CurriculumProfile,'subject'|'topic'>>={
 physics:{
  concepts:['Physical quantities and units','Forces and interactions','Energy and momentum','Modelling and equations','Experimental evidence'],
  lesson:'Physics explains physical systems using models, measurable quantities and relationships between them. Start by identifying the system and the quantities involved, choose consistent units, then select the governing relationship. Check assumptions and units before trusting a numerical result.\n\nFor a specific test, the learner path should then narrow to the requested topic and its prerequisites rather than treating the whole subject as one lesson.',
  graph:graph([{id:'quantities',name:'Physical quantities',description:'Measured properties with units.'},{id:'models',name:'Physical models',description:'Simplified representations of systems.'},{id:'equations',name:'Equations',description:'Relationships connecting physical quantities.'},{id:'evidence',name:'Experimental evidence',description:'Measurements used to test models.'}], [{from:'quantities',to:'equations',reason:'Equations operate on defined quantities.'},{from:'models',to:'equations',reason:'Models determine which relationships are appropriate.'},{from:'quantities',to:'evidence',reason:'Experiments require measurable quantities.'}]),
  questions:[{type:'choice',topic:'Physical quantities',prompt:'When solving a physics problem, what should you establish before substituting numbers?',options:['The relevant quantities and units','The final answer only','A random equation','The hardest possible method'],answer:'The relevant quantities and units',explanation:'Identifying quantities and units prevents using the wrong relationship and catches dimensional errors.'},{type:'concept',topic:'Physical models',prompt:'Explain why a physics model can be useful even though it simplifies reality.',answer:'simplify predict test',explanation:'Models deliberately simplify a system so useful predictions can be made and tested against evidence.'}]
 },
 chemistry:{
  concepts:['Atomic structure','Bonding and structure','Chemical quantities','Reactivity','Chemical evidence'],
  lesson:'Chemistry connects microscopic structure to observable properties and reactions. A strong learning path moves from particles and structure to bonding, quantities, reaction patterns and evidence. Equations and calculations should always be interpreted chemically, not treated as isolated arithmetic.\n\nThe requested topic should determine which branch is expanded next, with prerequisites surfaced when the learner struggles.',
  graph:graph([{id:'atomic-structure',name:'Atomic structure',description:'Particles, electron arrangement and the nucleus.'},{id:'bonding',name:'Bonding and structure',description:'How particles are connected and arranged.'},{id:'quantities',name:'Chemical quantities',description:'Moles, masses, concentrations and ratios.'},{id:'reactivity',name:'Reactivity',description:'How structure and conditions influence reactions.'}], [{from:'atomic-structure',to:'bonding',reason:'Bonding depends on electron structure.'},{from:'bonding',to:'reactivity',reason:'Structure influences chemical behaviour.'},{from:'quantities',to:'reactivity',reason:'Reaction predictions require quantitative relationships.'}]),
  questions:[{type:'choice',topic:'Atomic structure',prompt:'Which information is most directly determined by an element’s atomic number?',options:['Number of protons','Number of neutrons','Number of molecules','Mass of every isotope'],answer:'Number of protons',explanation:'Atomic number is defined by the number of protons in the nucleus.'},{type:'concept',topic:'Bonding and structure',prompt:'Explain why bonding and structure help predict a substance’s properties.',answer:'structure bonding properties',explanation:'The way particles are bonded and arranged controls many physical and chemical properties.'}]
 },
 mathematics:{
  concepts:['Definitions and notation','Algebraic relationships','Functions and representations','Proof and reasoning','Problem-solving strategy'],
  lesson:'Mathematics is built from precise definitions, representations and logical relationships. A useful study path begins with the definitions and notation for the requested topic, connects them to algebraic or graphical representations, then moves into increasingly demanding problems.\n\nWhen an answer is wrong, Cortex should inspect the reasoning chain rather than only repeating the final question.',
  graph:graph([{id:'definitions',name:'Definitions and notation',description:'Precise mathematical language.'},{id:'algebra',name:'Algebraic relationships',description:'Manipulating expressions and equations.'},{id:'functions',name:'Functions and representations',description:'Relationships represented symbolically and graphically.'},{id:'reasoning',name:'Proof and reasoning',description:'Justifying mathematical conclusions.'}], [{from:'definitions',to:'algebra',reason:'Algebra relies on precise definitions and notation.'},{from:'algebra',to:'functions',reason:'Many functions are expressed and transformed algebraically.'},{from:'definitions',to:'reasoning',reason:'Proof depends on precise statements.'}]),
  questions:[{type:'choice',topic:'Problem-solving strategy',prompt:'What is usually the strongest first step when facing an unfamiliar mathematical problem?',options:['Identify what is known, what is required, and the relevant definitions','Guess an answer immediately','Expand every expression at random','Ignore the conditions'],answer:'Identify what is known, what is required, and the relevant definitions',explanation:'Clarifying the givens, target and definitions creates a valid route into the problem.'},{type:'concept',topic:'Proof and reasoning',prompt:'What makes a mathematical argument a proof rather than a guess?',answer:'logical justified general',explanation:'A proof gives a logically justified argument that establishes the result under the stated assumptions.'}]
 },
 'computer science':{
  concepts:['Abstraction and decomposition','Data representation','Algorithms','Programming and systems','Testing and complexity'],
  lesson:'Computer science studies information, computation and systems. A strong learning path moves from abstraction and representation into algorithms, implementation, testing and performance. The right explanation depends on whether the learner is reasoning about data, code, algorithms or architecture.\n\nCortex should diagnose which layer is weak before selecting the next task.',
  graph:graph([{id:'abstraction',name:'Abstraction and decomposition',description:'Breaking complex problems into manageable models.'},{id:'data',name:'Data representation',description:'How information is encoded and structured.'},{id:'algorithms',name:'Algorithms',description:'Finite procedures for solving problems.'},{id:'programming',name:'Programming and systems',description:'Implementing computational ideas.'},{id:'testing',name:'Testing and complexity',description:'Checking correctness and analysing resources.'}], [{from:'abstraction',to:'algorithms',reason:'Algorithms begin with a clearly decomposed problem.'},{from:'data',to:'algorithms',reason:'Algorithms operate on represented data.'},{from:'algorithms',to:'programming',reason:'Programs implement algorithms.'},{from:'algorithms',to:'testing',reason:'Testing checks algorithmic behaviour and correctness.'}]),
  questions:[{type:'choice',topic:'Algorithms',prompt:'What is an algorithm?',options:['A finite sequence of steps for solving a problem','Any computer file','A programming language','A hardware component'],answer:'A finite sequence of steps for solving a problem',explanation:'An algorithm specifies a finite procedure for transforming inputs toward a desired result.'},{type:'concept',topic:'Testing and complexity',prompt:'Why can an algorithm be correct but still impractical?',answer:'resource time complexity',explanation:'An algorithm may produce correct results while requiring too much time or memory at useful input sizes.'}]
 },
 biology:{
  concepts:['Cells and organisation','Biological molecules','Processes and systems','Genetics and information','Evidence and variation'],
  lesson:'Biology explains living systems across scales, from molecules and cells to organisms and populations. Study should connect structure to function, processes to conditions, and observations to biological explanations.\n\nCortex should use the learner’s requested topic to select the relevant biological system and prerequisite concepts.',
  graph:graph([{id:'cells',name:'Cells and organisation',description:'Basic units and organisation of living systems.'},{id:'molecules',name:'Biological molecules',description:'Molecules that support structure and processes.'},{id:'processes',name:'Processes and systems',description:'Interactions that sustain living systems.'},{id:'genetics',name:'Genetics and information',description:'Biological information and inheritance.'}], [{from:'molecules',to:'processes',reason:'Many biological processes depend on molecular structure.'},{from:'cells',to:'processes',reason:'Processes occur within organised biological systems.'},{from:'genetics',to:'cells',reason:'Genetic information influences cellular function.'}]),
  questions:[{type:'choice',topic:'Cells and organisation',prompt:'Why is structure important when studying cells?',options:['Structure constrains and supports function','Structure has no relationship to function','Only cell colour matters','It determines the weather'],answer:'Structure constrains and supports function',explanation:'Cell structures are organised to carry out particular functions and interactions.'},{type:'concept',topic:'Evidence and variation',prompt:'Why is biological variation important when interpreting evidence?',answer:'variation populations samples conclusions',explanation:'Variation means samples and populations are not identical, so evidence must be interpreted with that spread in mind.'}]
 }
};

function detect(subject:string){const s=subject.toLowerCase();if(/computer science|computing|programming|coding|algorithm/.test(s))return 'computer science';if(/chem|organic|inorganic|electrochem|stoichiom/.test(s))return 'chemistry';if(/math|calculus|algebra|trigonometry|statistics|mechanics/.test(s))return 'mathematics';if(/bio|cell|genetics|ecology|physiology/.test(s))return 'biology';if(/physics|mechanics|electricity|waves|deformation|motion|forces/.test(s))return 'physics';return 'generic'}

export function buildCurriculum(goal:string):CurriculumProfile{
 const subjectKey=detect(goal);
 const subject=subjectKey==='generic'?'General study':subjectKey.replace(/\b\w/g,c=>c.toUpperCase());
 const topic=extractTopic(goal,subjectKey);
 if(subjectKey==='generic'){
  return {subject,topic,concepts:[`Core ideas in ${topic}`,'Definitions and terminology','Relationships and reasoning','Application and practice','Evidence of understanding'],lesson:`Cortex has identified ${topic} as the current study target. The first pass will establish the key ideas, vocabulary, relationships and applications needed to work with the topic.\n\nBecause no specialised curriculum profile was assumed, the system keeps the structure generic rather than pretending it knows a syllabus it has not been given. Add notes, a syllabus, textbook material or a more specific objective for deeper grounding.`,graph:graph([{id:'core',name:`Core ideas in ${topic}`,description:'The central knowledge needed for the requested topic.'},{id:'terms',name:'Definitions and terminology',description:'Language needed to describe the topic precisely.'},{id:'relationships',name:'Relationships and reasoning',description:'Connections between the topic’s ideas.'},{id:'application',name:'Application and practice',description:'Using the knowledge in problems or examples.'}], [{from:'terms',to:'relationships',reason:'Precise terminology is needed to reason about relationships.'},{from:'core',to:'relationships',reason:'Relationships connect the core ideas.'},{from:'relationships',to:'application',reason:'Application depends on understanding the underlying relationships.'}]),questions:[{type:'concept',topic:`Core ideas in ${topic}`,prompt:`In your own words, what is the central idea you need to understand about ${topic}?`,answer:topic.toLowerCase(),explanation:'A useful answer should accurately identify and explain the central idea of the requested topic.'},{type:'choice',topic:'Definitions and terminology',prompt:'What is the best way to handle unfamiliar terminology while studying?',options:['Define it precisely and connect it to the topic','Skip every unfamiliar term','Memorise the spelling only','Guess its meaning and never check'],answer:'Define it precisely and connect it to the topic',explanation:'Precise terminology reduces ambiguity and makes later reasoning more reliable.'}]};
 }
 const p=profiles[subjectKey];return {...p,subject,topic};
}

function extractTopic(goal:string,subjectKey:string){
 const cleaned=goal.replace(/\s+/g,' ').trim();
 const patterns=[/on\s+(.+?)(?:\.|,|$)/i,/about\s+(.+?)(?:\.|,|$)/i,/cover(?:ing)?\s+(.+?)(?:\.|,|$)/i,/study\s+(.+?)(?:\.|,|$)/i];
 for(const pattern of patterns){const match=cleaned.match(pattern);if(match?.[1])return match[1].trim().replace(/^(the|required|all)\s+/i,'');}
 if(subjectKey!=='generic')return `${subjectKey} fundamentals`;
 return cleaned.slice(0,90)||'the requested subject';
}
