import {LearnerModel,updateLearnerModel,weakestTopic} from './learner-state';
import {PHYSICS_DEFORMATION_GRAPH,KnowledgeGraph,prerequisiteNames,conceptId,inferPrerequisiteGap} from './knowledge-graph';

export type AgentId = 'researcher'|'tutor'|'challenger'|'examiner';
export type Phase = 'idle'|'running'|'synthesizing'|'complete';
export type QuestionType = 'numeric'|'choice'|'concept';
export type EventKind = 'ROOM_STARTED'|'RESEARCH_UPDATED'|'LESSON_PROPOSED'|'CONCEPT_GAP_DETECTED'|'MISCONCEPTION_DETECTED'|'QUESTION_CREATED'|'ANSWER_SUBMITTED'|'ASSESSMENT_UPDATED'|'AGENT_REACTED'|'ROOM_SYNTHESIS_REQUESTED'|'ROOM_COMPLETED'|'PRACTICE_REQUESTED'|'LESSON_REFRAMED';
export type RoomEvent={id:number;kind:EventKind;agent?:AgentId;message:string;time:number};
export type Question={type:QuestionType;prompt:string;options?:string[];answer:string;explanation:string;topic:string};
export type RoomState={goal:string;topic:string;phase:Phase;events:RoomEvent[];concepts:string[];lesson:string;gap:string;question:Question|null;answer:string;assessment:string;plan:string;activity:Record<AgentId,string>;progress:Record<AgentId,number>;mastery:number;questionNumber:number;questionsAnswered:number;questionAttempts:number;correctAnswers:number;accepted:boolean;lastCorrect:boolean|null;needsReview:boolean;feedbackCount:number;learnerModel:LearnerModel;knowledgeGraph:KnowledgeGraph;prerequisiteGap:string|null};

const wait=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms));
const initial=(goal:string):RoomState=>({goal,topic:goal,phase:'idle',events:[],concepts:[],lesson:'',gap:'',question:null,answer:'',assessment:'',plan:'',activity:{researcher:'Standby',tutor:'Standby',challenger:'Standby',examiner:'Standby'},progress:{researcher:0,tutor:0,challenger:0,examiner:0},mastery:0,questionNumber:0,questionsAnswered:0,questionAttempts:0,correctAnswers:0,accepted:false,lastCorrect:null,needsReview:false,feedbackCount:0,learnerModel:{},knowledgeGraph:PHYSICS_DEFORMATION_GRAPH,prerequisiteGap:null});

function normalize(raw:string){return raw.trim().replace(/[⁰¹²³⁴⁵⁶⁷⁸⁹⁻]/g,c=>({'⁰':'0','¹':'1','²':'2','³':'3','⁴':'4','⁵':'5','⁶':'6','⁷':'7','⁸':'8','⁹':'9','⁻':'-'} as Record<string,string>)[c]??c).replace(/,/g,'').replace(/\s+/g,'').replace(/×/g,'x').replace(/−/g,'-').toLowerCase();}
function parseNumericAnswer(raw:string){let n=normalize(raw).replace(/pa$/,'').replace(/pascal(s)?$/,'').replace(/\*{1,2}/g,'*');const sci=n.match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+))(?:x\*?10\^|10\^)([+-]?\d+)$/);if(sci)return Number(sci[1])*10**Number(sci[2]);const exp=n.match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+))[e]([+-]?\d+)$/);if(exp)return Number(exp[1])*10**Number(exp[2]);const suffix=n.match(/^([+-]?(?:\d+(?:\.\d*)?|\.\d+))(k|m|g)$/);if(suffix){const multipliers:Record<string,number>={k:1e3,m:1e6,g:1e9};return Number(suffix[1])*multipliers[suffix[2]]}const plain=n.match(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/);return plain?Number(plain[0]):Number.NaN;}
function cleanText(raw:string){return normalize(raw).replace(/[^a-z0-9.]/g,'');}

const QUESTIONS:Question[]=[
 {type:'numeric',topic:'Stress',prompt:'A wire has a cross-sectional area of 2.0 × 10⁻⁶ m² and is pulled with a force of 40 N. Calculate the stress in the wire.',answer:'20000000',explanation:'Stress = force ÷ area = 40 ÷ (2.0 × 10⁻⁶) = 2.0 × 10⁷ Pa.'},
 {type:'choice',topic:'Strain',prompt:'Which expression correctly defines tensile strain?',options:['Force ÷ cross-sectional area','Extension ÷ original length','Force ÷ extension','Stress ÷ strain'],answer:'Extension ÷ original length',explanation:'Tensile strain is extension divided by original length. It has no unit.'},
 {type:'numeric',topic:'Strain',prompt:'A wire of original length 2.0 m extends by 0.50 mm. Calculate the strain.',answer:'0.00025',explanation:'0.50 mm = 5.0 × 10⁻⁴ m. Strain = extension ÷ original length = 2.5 × 10⁻⁴.'},
 {type:'numeric',topic:'Young modulus',prompt:'A material has a stress of 6.0 × 10⁷ Pa and a strain of 3.0 × 10⁻⁴. Calculate its Young modulus.',answer:'200000000000',explanation:'Young modulus E = stress ÷ strain = (6.0 × 10⁷) ÷ (3.0 × 10⁻⁴) = 2.0 × 10¹¹ Pa.'},
 {type:'concept',topic:'Elastic behaviour',prompt:'State the difference between the elastic limit and the breaking point.',answer:'elastic limit breaking point',explanation:'The elastic limit is the point beyond which permanent deformation occurs. The breaking point is where the material fractures. A material can permanently deform before it breaks.'},
 {type:'choice',topic:'Elastic behaviour',prompt:'A wire is loaded beyond its elastic limit but is not yet broken. What happens when the load is removed?',options:['It returns completely to its original length','It remains permanently deformed','It immediately fractures','Its mass decreases'],answer:'It remains permanently deformed',explanation:'Beyond the elastic limit, removing the load does not restore the original shape completely.'},
 {type:'numeric',topic:'Stress',prompt:'A force of 150 N acts on an area of 3.0 × 10⁻⁶ m². Calculate the stress.',answer:'50000000',explanation:'Stress = 150 ÷ (3.0 × 10⁻⁶) = 5.0 × 10⁷ Pa.'}
];

export class StudyRoom {
 state:RoomState; private listeners=new Set<(s:RoomState)=>void>(); private eventId=0; private questionAttempted=false;
 constructor(goal:string){this.state=initial(goal)}
 subscribe(fn:(s:RoomState)=>void){this.listeners.add(fn);fn(this.state);return()=>{this.listeners.delete(fn)}}
 private emit(kind:EventKind,message:string,agent?:AgentId){this.state={...this.state,events:[...this.state.events,{id:++this.eventId,kind,agent,message,time:Date.now()}]};this.listeners.forEach(f=>f(this.state))}
 private patch(p:Partial<RoomState>){this.state={...this.state,...p};this.listeners.forEach(f=>f(this.state))}
 private agent(agent:AgentId,activity:string,progress:number){this.patch({activity:{...this.state.activity,[agent]:activity},progress:{...this.state.progress,[agent]:progress}})}
 async run(){if(this.state.phase==='running')return;this.questionAttempted=false;this.patch({phase:'running',accepted:false,lastCorrect:null,needsReview:false,assessment:'',answer:'',question:null,questionNumber:0,questionsAnswered:0,questionAttempts:0,correctAnswers:0,mastery:0,feedbackCount:0,learnerModel:{},prerequisiteGap:null});this.emit('ROOM_STARTED','Four specialised agents are working concurrently on the study objective.');await Promise.all([this.researcher(),this.tutor(),this.challenger(),this.examiner()]);this.patch({phase:'synthesizing'});this.emit('ROOM_SYNTHESIS_REQUESTED','The agents are consolidating the current knowledge state into the first diagnostic step.');await wait(350);this.patch({plan:'Complete the diagnostic, review any weak concept, then continue through targeted practice until the session reaches a stable understanding.'});this.emit('ROOM_COMPLETED','Initial study pass complete. The diagnostic remains active so the session can continue.');this.patch({phase:'complete'});}
 private async researcher(){const a:'researcher'='researcher';this.agent(a,'Mapping prerequisites',12);await wait(300);this.agent(a,'Identifying core concepts',42);await wait(420);this.patch({concepts:['Stress = force / area','Strain = extension / original length','Young modulus = stress / strain','Elastic limit → permanent deformation','Breaking point → fracture']});this.agent(a,'Knowledge graph mapped',100);this.emit('RESEARCH_UPDATED',`Knowledge map updated with ${this.state.knowledgeGraph.nodes.length} concepts and prerequisite relationships.`,a)}
 private async tutor(){const a:'tutor'='tutor';this.agent(a,'Structuring instruction',15);await wait(500);this.agent(a,'Drafting explanation',48);await wait(400);this.patch({lesson:'Deformation describes how a material changes shape when a force acts on it. Stress measures force per unit area. Strain measures fractional extension. Young modulus is the ratio of stress to strain, E = stress / strain. Within the elastic region, removing the force restores the original shape. Beyond the elastic limit, permanent deformation can occur.\n\nThe elastic limit marks the onset of permanent deformation. The breaking point is the point of fracture. These are not the same point.'});this.agent(a,'Instruction under review',72);this.emit('LESSON_PROPOSED','Instruction prepared and submitted for conceptual review.',a);await wait(650);if(this.state.gap){this.agent(a,'Addressing review finding',88);await wait(400);this.patch({lesson:this.state.lesson+'\n\nReview confirmed the distinction above and kept it explicit for assessment.'});this.agent(a,'Instruction updated',100);this.emit('AGENT_REACTED','Tutor revised the instruction after the review agent identified a conceptual gap.',a)}else this.agent(a,'Instruction accepted',100)}
 private async challenger(){const a:'challenger'='challenger';this.agent(a,'Checking conceptual risks',18);await wait(680);this.agent(a,'Testing definitions',55);await wait(380);this.patch({gap:'Elastic limit and breaking point must remain conceptually distinct.'});this.agent(a,'Review finding issued',76);this.emit('CONCEPT_GAP_DETECTED','Review identified a likely confusion between elastic limit and breaking point.',a);await wait(300);this.agent(a,'Verifying instructional response',100);this.emit('AGENT_REACTED','Review confirmed that the instruction was revised in response to its finding.',a)}
 private async examiner(){const a:'examiner'='examiner';this.agent(a,'Selecting diagnostic',20);await wait(520);this.patch({question:{...QUESTIONS[0]},questionNumber:1});this.agent(a,'Diagnostic presented',58);this.emit('QUESTION_CREATED','Diagnostic selected to test direct application of the stress relationship.',a);await wait(520);this.agent(a,'Preparing assessment',82);await wait(220);this.patch({assessment:'Enter the value with units if known. Working is recommended for calculation questions.'});this.agent(a,'Assessment ready',100);this.emit('ASSESSMENT_UPDATED','Diagnostic assessment is ready for the learner response.',a)}
 submitAnswer(answer:string){if(!this.state.question||this.state.accepted||!answer.trim())return;this.patch({answer});this.emit('ANSWER_SUBMITTED',`Learner submitted: ${answer}`);const q=this.state.question;let correct=false;if(q.type==='numeric'){const value=parseNumericAnswer(answer);const expected=Number(q.answer);correct=Number.isFinite(value)&&Math.abs(value-expected)<=Math.max(Math.abs(expected)*1e-6,1e-10)}else if(q.type==='choice')correct=cleanText(answer)===cleanText(q.answer);else{const text=cleanText(answer);correct=text.includes('elasticlimit')&&text.includes('breakingpoint')}
 const questionAttempts=this.state.questionAttempts+1;const firstAttempt=!this.questionAttempted;this.questionAttempted=true;const questionsAnswered=this.state.questionsAnswered+(firstAttempt?1:0);const correctAnswers=this.state.correctAnswers+(correct&&!this.state.accepted?1:0);const mastery=Math.round((correctAnswers/questionsAnswered)*100);const feedbackCount=this.state.feedbackCount+1;const learnerModel=updateLearnerModel(this.state.learnerModel,q.topic,correct);const weakTopics=Object.values(learnerModel).filter(x=>x.needsReview).map(x=>x.topic);const prereqId=inferPrerequisiteGap(this.state.knowledgeGraph,q.topic,weakTopics);const prereqName=prereqId?this.state.knowledgeGraph.nodes.find(n=>n.id===prereqId)?.name??null:null;const weakest=weakestTopic(learnerModel);this.patch({questionsAnswered,questionAttempts,correctAnswers,mastery,accepted:correct,lastCorrect:correct,needsReview:!correct,feedbackCount,learnerModel,prerequisiteGap:prereqName,assessment:correct?`Correct. ${q.explanation}`:`Needs revision. ${q.explanation}`});this.emit('ASSESSMENT_UPDATED',correct?`Correct response recorded for ${q.topic}.`:`Response requires revision in ${q.topic}.`,'examiner');if(!correct){const message=prereqName?`Gap detected in ${q.topic}. Prerequisite evidence points to ${prereqName} as a review target.`:`Learner response indicates a gap in ${q.topic}. A targeted follow-up is required.`;this.patch({plan:prereqName?`Reinforce prerequisite: ${prereqName}, then return to ${q.topic}.`:`Review ${q.topic}, then retry or continue with a targeted question.`});this.emit('CONCEPT_GAP_DETECTED',message,'challenger');this.agent('challenger','Gap confirmed from learner evidence',100);this.agent('tutor',prereqName?`Adapting around prerequisite: ${prereqName}`:'Reviewing learner response',100)}else{this.patch({plan:weakest?`Evidence updated. ${weakest} is currently the highest-priority review area.`:`${q.topic} demonstrated. Continue to the next concept and increase difficulty.`});this.emit('AGENT_REACTED',`Assessment result shared with the study room. Learner evidence now updates future question selection.`,'tutor');this.agent('examiner','Result recorded for adaptation',100)}}
 requestPractice(){if(this.state.phase==='running'||!this.state.question)return;const current=this.state.question;const reinforce=this.state.needsReview;const priority=weakestTopic(this.state.learnerModel);let nextIndex=this.state.questionNumber%QUESTIONS.length;if(reinforce){const target=this.state.prerequisiteGap??current.topic;const targetIndex=QUESTIONS.findIndex((q,i)=>i!==this.state.questionNumber-1&&q.topic===target);const sameTopic=QUESTIONS.findIndex((q,i)=>i!==this.state.questionNumber-1&&q.topic===current.topic);if(targetIndex>=0)nextIndex=targetIndex;else if(sameTopic>=0)nextIndex=sameTopic;}else if(priority){const priorityIndex=QUESTIONS.findIndex(q=>q.topic===priority&&q.topic!==current.topic);if(priorityIndex>=0)nextIndex=priorityIndex;}const next=QUESTIONS[nextIndex];this.questionAttempted=false;this.patch({question:{...next},questionNumber:this.state.questionNumber+1,answer:'',assessment:'',accepted:false,lastCorrect:null,needsReview:false,phase:'complete',prerequisiteGap:null});this.emit('PRACTICE_REQUESTED',`Follow-up ${this.state.questionNumber}: ${next.topic} selected from the current learner evidence.`,'examiner');this.agent('examiner','Preparing evidence-driven follow-up',68);this.agent('challenger',reinforce?'Checking prerequisite target':'Checking next concept',68);this.agent('tutor',reinforce?'Adapting instruction to the learner gap':'Planning the next concept',68);this.emit('QUESTION_CREATED',`Question selected to ${reinforce?'reinforce':'extend'} ${next.topic}.`,'examiner')}
 reframeLesson(){const repaired=this.state.prerequisiteGap?`Prerequisite focus: ${this.state.prerequisiteGap}. Build that concept first, then connect it back to ${this.state.question?.topic??'the current topic'}.\n\n${this.state.gap?'Key distinction: the elastic limit marks the onset of permanent deformation. The breaking point is the point of fracture. A material can permanently deform before it breaks.':'Key relationships: stress = force / area, strain = extension / original length, Young modulus = stress / strain.'}`:this.state.gap?`Key distinction: the elastic limit marks the onset of permanent deformation. The breaking point is the point of fracture. A material can permanently deform before it breaks.`:'Key relationships: stress = force / area, strain = extension / original length, Young modulus = stress / strain.';this.patch({lesson:repaired});this.emit('LESSON_REFRAMED','Instruction was rephrased around the current prerequisite or conceptual gap.','tutor')}
 reset(goal:string){this.state=initial(goal);this.eventId=0;this.questionAttempted=false;this.listeners.forEach(f=>f(this.state))}
}
